### ISSUE TITLE
404 fetching followed repositories 

### ISSUE THREAD

**Issue by jorgectf** [gagliardetto/lgtm-cli#2]
I'm opening this issue to not mess the PRs and to have everything organized.

I've had problems to fetch my followed repos list from lgtm (https://lgtm.com/internal_api/v0.2/getMyProjects) when the amount of them gets over 3-4k. Does that also happen to you or perhaps I've gone through some kind of rate limit?

```
$ lgtm followed
[INFO][0|XX:XX:XX|Xms] Getting list of followed projects...
panic: status code is 404; body:

 {"status":"error","error":"not found","message":"not found"}
```

**Comment by gagliardetto** [comment]
Does this still not work? Do other commands work, but this not? (Same terminal window)

**Comment by jorgectf** [comment]
The problem is not in the option but in the request itself. While doing any other option in which the followed repos are needed, the 404 appears too. It also happens in the browser I guess, since projects don't get listed (and the request done to fetch those repos also arise a 404). Perhaps the issue is related to LGTM itself? Have you encountered that error while having 5k repos or more?

**Comment by gagliardetto** [comment]
I'm following 6K repos. Will try to reproduce.

**Comment by gagliardetto** [comment]
I think its a timeout. Their front-end proxies send the request to their backend servers, but the backend is so slow that the request timeouts and we get a 404.

**Comment by jorgectf** [comment]
That's possible. Should we contact them or something like that?

**Comment by jorgectf** [comment]
I've created [an issue](https://github.com/github/codeql/issues/4896).

**Comment by gagliardetto** [comment]
Now the getMyProjects API seems to work again.

**Comment by jorgectf** [comment]
> Now API it seems to work again.

Not for me ;(

**Comment by gagliardetto** [comment]
Try going to https://lgtm.com/dashboard and refreshing a couple times

**Comment by jorgectf** [comment]
> Try going to https://lgtm.com/dashboard and refreshing a couple times

Neither :/

**Comment by jorgectf** [comment]
Feel free to close this issue if you think the one opened in github's codeql repo is enough 👍

**Comment by mrthankyou** [comment]
For anyone experiencing this issue, it looks like even if you close and then re-open you LGTM account that has been bricked due to following too many repos, this issue will still occur when connecting with the API.

The only solution I have is to create a different account.

**Comment by gagliardetto** [comment]
The solution is to ... cleanup the followed projects list.

You can compile a summary list of repos you (think) you follow, and then unfollow them (even if you're not sure you are following them).

```bash
lgtm --ignore-followed-errors unfollow -f=all_repos.txt
```

This will clean up your followed projects list, and make lgtm.com usable again.
