### ISSUE TITLE
Error when downloading go package via go get

### ISSUE THREAD

**Issue by mrthankyou** [gagliardetto/lgtm-cli#8]
When running `go get -u github.com/gagliardetto/lgtm-cli` I receive the following error message:

```
# github.com/gagliardetto/gh-client
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:394:2: too many arguments to return
	have (io.ReadCloser, *github.Response, error)
	want (io.ReadCloser, error)
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:877:21: cannot use &repos.Repositories[repIndex] (type **github.Repository) as type *github.Repository in append
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:981:11: calling method GetStargazersCount with receiver repo (type **github.Repository) requires explicit dereference
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:984:14: calling method GetFullName with receiver repo (type **github.Repository) requires explicit dereference
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:987:27: calling method GetStargazersCount with receiver repo (type **github.Repository) requires explicit dereference
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:989:22: cannot use repo (type **github.Repository) as type *github.Repository in append
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:1104:11: calling method GetStargazersCount with receiver repo (type **github.Repository) requires explicit dereference
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:1107:21: cannot use repo (type **github.Repository) as type *github.Repository in append
/Users/hacker/go/src/github.com/gagliardetto/gh-client/github.go:1192:27: cannot use &repos.CodeResults[repIndex] (type **github.CodeResult) as type *github.CodeResult in append
```

I'm running on Mac Big Sur 11.1. I have successfully used `go get` before so I don't _think_ this is a local configuration issue. Please let me know if you have any follow-up questions.

**Comment by gagliardetto** [comment]
Hi @mrthankyou 

What version of go are you running? 

`$ go version`

**Comment by gagliardetto** [comment]
I suggest trying the alternative method (the git clone one) in https://github.com/gagliardetto/lgtm-cli#install

**Comment by mrthankyou** [comment]
`go1.15.3 darwin/amd64`

I'll try the alternative method.

**Comment by gagliardetto** [comment]
Did the second method work successfully for you?

**Comment by mrthankyou** [comment]
I was able to download the package via go get but am now running into a separate issue where whenever I run `lgtm` in my terminal it says the command isn't found. I believe this is a configuration issue on my end. I'm happy to close this if you are since you updated the instructions in the README and those instructions worked for me.

**Comment by gagliardetto** [comment]
Great to hear that.

Maybe `$GOPATH/bin` is not in your `PATH`? https://golang.org/doc/gopath_code.html#GOPATH

**Comment by gagliardetto** [comment]
The `$ make install` command compiles and installs the `lgtm` binary to `$GOPATH/bin`.

`$ export PATH=$PATH:$(go env GOPATH)/bin` should fix the `command not found` problem (need to put it somewhere persistent, though).

**Comment by gagliardetto** [comment]
Closing. Please reopen in case you encounter other issues.
